### ISSUE TITLE
Module 'statcord' has no 'Client' member

### ISSUE THREAD

**Issue by lpkeates** [labdiscord/statcord.py#11]
For some reason, when I'm using a cog with my statcord.py, it doesn't like the .Client member. Is there something wrong with the code? Here is the code:
`from discord.ext import commands
import statcord

class StatcordPost(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.key = "statcord.com-ADDYOURKEYHERE"
        self.api = statcord.Client(self.bot,self.key)
        self.api.start_loop()
    
    @commands.Cog.listener()
    async def on_command(self,ctx):
        self.api.command_run(ctx)

def setup(bot):
    bot.add_cog(StatcordPost(bot))`

**Comment by aaix** [comment]
Do you have something called statcord in your directory?

**Comment by lpkeates** [comment]
Yes Sent from Mail for Windows 10 From: aaixSent: 28 August 2020 15:43To: labdiscord/statcord.pyCc: MrMudkip; AuthorSubject: Re: [labdiscord/statcord.py] Module 'statcord' has no 'Client' member (#11) Do you have something called statcord in your directory?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by taynotfound** [comment]
Oi CSS spam lmao

**Comment by anishanne** [comment]
> Yes 

Ok rename that from "statcord.py" to "stats.py".
